### ISSUE TITLE
Custom hardware?

### ISSUE THREAD

**Issue by sskorol** [Hatsuduki/minipupper_pythontest#1]
Hi @Hatsuduki,

I see you use `pyservohat` library in your experiments. Just wondering if you replaced the default minipupper servo controller with some other hardware? If yes, which one? Otherwise, do you mean this library works with minipupper's custom board out of the box?

Thanks,
Sergey

**Comment by Hatsuduki** [comment]
I use the PyServoHat library with a default MiniPupper board.

**Comment by Hatsuduki** [comment]
But if you use genuine pre-built image and the kernel is using servo motor driver, I couldn’t control it so I commented out lines related to that.
